### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bakkot** [ksed786/Scriptie#2]
Hi, this is Kevin Gibbons.

This mostly looks great. Thanks for putting it together! I had a few comments, listed below.

---

It's currently phrased as "What are the possible outputs?", but then it has a mix of [variables being declared](https://github.com/ksed786/Scriptie/blob/ee51914897da55279db4bf7e99d37e3bf5f5d13f/script.js#L35-L38) or [initialized](https://github.com/ksed786/Scriptie/blob/ee51914897da55279db4bf7e99d37e3bf5f5d13f/script.js#L99-L112) (where presumably the "output" is "what value does the variable get") and [functions being defined](https://github.com/ksed786/Scriptie/blob/ee51914897da55279db4bf7e99d37e3bf5f5d13f/script.js#L73-L82) (where presumably the "output" is "what would this function do if called").

It would be better, I think, to ask the more precise questions. That is, rather than "what is the output", to ask "what value does this variable have after this code runs" or "what would this function do if called", as appropriate.

---

The spice rack example is pretty complicated. Maybe a simpler example?

```js
let people = [
  { name: 'Alice', age: '42' },
  { name: 'Bob', age: 'unknown' },
  { name: 'Carol', age: '45' },
];
let maxAge = -Infinity;
for (let person of people) {
  let age = do {
    if (person.age == 'unknown') {
      continue;
    }
    parseInt(item.age)
  };
  if (age > maxAge) {
    maxAge = age;
  }
}
```

If you keep the spice rack example, some nits:
- [this bit](https://github.com/ksed786/Scriptie/blob/ee51914897da55279db4bf7e99d37e3bf5f5d13f/script.js#L100) has a for-in loop. The more common construction is [for-of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of). (Since `spiceRack` isn't defined, you can just change `in` to `of` and leave the rest alone.)
- there's a typo [here](https://github.com/ksed786/Scriptie/blob/ee51914897da55279db4bf7e99d37e3bf5f5d13f/script.js#L103) (`cinnimon` should be `cinnamon`)

---

Some other minor things:
- [this question](https://github.com/ksed786/Scriptie/blob/ee51914897da55279db4bf7e99d37e3bf5f5d13f/script.js#L121-L126) has messed up indentation (the last four lines should be a level deeper)
- that question also has `let AmountOfShoes:` instead of `let AmountOfShoes =`
- [this question](https://github.com/ksed786/Scriptie/blob/ee51914897da55279db4bf7e99d37e3bf5f5d13f/script.js#L121-L126) has `bool playOutside: do {` instead of `let playOutside = do {`
- that question and the next several have `yes` and `no` rather than `true` and `false`

**Comment by ksed786** [comment]
Thank you for the feedback , applied the changes
